<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>ACCSync</ApplicationTitle>
    <Product>ACCSync</Product>
    <StartupObject>ACCSync.App</StartupObject>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <SelfContained>true</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HttpClientFactory" Version="1.0.0" />
  </ItemGroup>

</Project>
